#!/usr/bin/env node
/**
 * Generates CDN-ready JSON files for football entities.
 * Run: node scripts/build_football_entities.js
 *
 * Output:
 *   entities/football/teams/_index.json  + 48 team files
 *   entities/football/players/_index.json + 35 player files
 *
 * The nightly GitHub Actions workflow runs this after any manual data edits,
 * allowing the app to fetch live stats when WORLD_CUP_LIVE=true.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

const TEAMS = [
  { id:'argentina', name:'Argentina', shortName:'ARG', categoryId:'football', subCategoryId:'teams', emoji:'🇦🇷',
    stats:{ fifa_rank:1, wc_titles:3, wc_appearances:19, win_rate_pct:62, avg_goals_per_game:1.9, avg_goals_conceded:0.9, unbeaten_streak:24, squad_avg_age:27.4, squad_market_value_m:850, wc_finals_appearances:6, continental_titles:17, team_trophies_total:20, wc_golden_boots:3, pressing_intensity:8, tactical_flexibility:9, player_synergy:9, youth_development:7, coach_rating:9, wc_knockout_win_rate_pct:67, penalty_shootout_wins:3, wc_clean_sheets:52, biggest_win_margin:6, global_fan_base_m:900, social_media_m:210 },
    meta:{ confederation:'CONMEBOL', coach:'Lionel Scaloni', wc_best:'Winners', form:'WWWDW', key_players:'L. Messi, J. Álvarez, R. De Paul, E. Martínez' },
    tags:['argentina','arg','albiceleste','south america','messi','conmebol'] },
  { id:'brazil', name:'Brazil', shortName:'BRA', categoryId:'football', subCategoryId:'teams', emoji:'🇧🇷',
    stats:{ fifa_rank:5, wc_titles:5, wc_appearances:22, win_rate_pct:64, avg_goals_per_game:2.1, avg_goals_conceded:0.8, unbeaten_streak:7, squad_avg_age:26.8, squad_market_value_m:960, wc_finals_appearances:7, continental_titles:22, team_trophies_total:28, wc_golden_boots:5, pressing_intensity:8, tactical_flexibility:8, player_synergy:8, youth_development:9, coach_rating:7, wc_knockout_win_rate_pct:72, penalty_shootout_wins:1, wc_clean_sheets:71, biggest_win_margin:8, global_fan_base_m:1200, social_media_m:280 },
    meta:{ confederation:'CONMEBOL', coach:'Dorival Júnior', wc_best:'Winners', form:'WDWWL', key_players:'Vinicius Jr., Rodrygo, L. Paquetá, Militão' },
    tags:['brazil','bra','seleção','canarinha','south america','conmebol'] },
  { id:'colombia', name:'Colombia', shortName:'COL', categoryId:'football', subCategoryId:'teams', emoji:'🇨🇴',
    stats:{ fifa_rank:9, wc_titles:0, wc_appearances:7, win_rate_pct:48, avg_goals_per_game:1.6, avg_goals_conceded:1.1, unbeaten_streak:28, squad_avg_age:26.2, squad_market_value_m:420, wc_finals_appearances:0, continental_titles:2, team_trophies_total:3, wc_golden_boots:1, pressing_intensity:7, tactical_flexibility:7, player_synergy:8, youth_development:7, coach_rating:8, wc_knockout_win_rate_pct:38, penalty_shootout_wins:0, wc_clean_sheets:14, biggest_win_margin:5, global_fan_base_m:120, social_media_m:40 },
    meta:{ confederation:'CONMEBOL', coach:'Néstor Lorenzo', wc_best:'Quarter-final', form:'WWWWW', key_players:'L. Díaz, J. Cuadrado, R. Arias, J. Lerma' },
    tags:['colombia','col','cafeteros','south america','conmebol'] },
  { id:'uruguay', name:'Uruguay', shortName:'URU', categoryId:'football', subCategoryId:'teams', emoji:'🇺🇾',
    stats:{ fifa_rank:14, wc_titles:2, wc_appearances:14, win_rate_pct:45, avg_goals_per_game:1.4, avg_goals_conceded:1.1, unbeaten_streak:5, squad_avg_age:27.1, squad_market_value_m:310, wc_finals_appearances:3, continental_titles:20, team_trophies_total:23, wc_golden_boots:1, pressing_intensity:7, tactical_flexibility:7, player_synergy:7, youth_development:7, coach_rating:8, wc_knockout_win_rate_pct:50, penalty_shootout_wins:2, wc_clean_sheets:30, biggest_win_margin:8, global_fan_base_m:60, social_media_m:20 },
    meta:{ confederation:'CONMEBOL', coach:'Marcelo Bielsa', wc_best:'Winners', form:'WDWLW', key_players:'F. Valverde, D. Núñez, R. Bentancur, J. Giménez' },
    tags:['uruguay','uru','celeste','south america','conmebol'] },
  { id:'ecuador', name:'Ecuador', shortName:'ECU', categoryId:'football', subCategoryId:'teams', emoji:'🇪🇨',
    stats:{ fifa_rank:31, wc_titles:0, wc_appearances:4, win_rate_pct:38, avg_goals_per_game:1.3, avg_goals_conceded:1.2, unbeaten_streak:4, squad_avg_age:25.6, squad_market_value_m:195, wc_finals_appearances:0, continental_titles:0, team_trophies_total:0, wc_golden_boots:0, pressing_intensity:6, tactical_flexibility:6, player_synergy:6, youth_development:7, coach_rating:7, wc_knockout_win_rate_pct:25, penalty_shootout_wins:0, wc_clean_sheets:8, biggest_win_margin:3, global_fan_base_m:30, social_media_m:12 },
    meta:{ confederation:'CONMEBOL', coach:'Sebastián Beccacece', wc_best:'Round of 16', form:'WWDWL', key_players:'E. Preciado, J. Plata, A. Caicedo, P. Ibarra' },
    tags:['ecuador','ecu','tri','south america','conmebol'] },
  { id:'venezuela', name:'Venezuela', shortName:'VEN', categoryId:'football', subCategoryId:'teams', emoji:'🇻🇪',
    stats:{ fifa_rank:27, wc_titles:0, wc_appearances:0, win_rate_pct:35, avg_goals_per_game:1.2, avg_goals_conceded:1.3, unbeaten_streak:7, squad_avg_age:24.8, squad_market_value_m:165, wc_finals_appearances:0, continental_titles:0, team_trophies_total:0, wc_golden_boots:0, pressing_intensity:6, tactical_flexibility:6, player_synergy:6, youth_development:6, coach_rating:6, wc_knockout_win_rate_pct:0, penalty_shootout_wins:0, wc_clean_sheets:0, biggest_win_margin:0, global_fan_base_m:25, social_media_m:10 },
    meta:{ confederation:'CONMEBOL', coach:'Fernando Batista', wc_best:'Group stage', form:'WDWWL', key_players:'Y. Bello, J. Martínez, S. Córdova, E. Herrera' },
    tags:['venezuela','ven','vinotinto','south america','conmebol'] },
  { id:'france', name:'France', shortName:'FRA', categoryId:'football', subCategoryId:'teams', emoji:'🇫🇷',
    stats:{ fifa_rank:2, wc_titles:2, wc_appearances:16, win_rate_pct:58, avg_goals_per_game:1.8, avg_goals_conceded:0.9, unbeaten_streak:9, squad_avg_age:26.5, squad_market_value_m:1100, wc_finals_appearances:3, continental_titles:3, team_trophies_total:5, wc_golden_boots:6, pressing_intensity:8, tactical_flexibility:8, player_synergy:8, youth_development:9, coach_rating:8, wc_knockout_win_rate_pct:63, penalty_shootout_wins:2, wc_clean_sheets:40, biggest_win_margin:7, global_fan_base_m:550, social_media_m:110 },
    meta:{ confederation:'UEFA', coach:'Didier Deschamps', wc_best:'Winners', form:'WWWWD', key_players:'K. Mbappé, O. Dembélé, A. Tchouaméni, T. Hernandez' },
    tags:['france','fra','les bleus','europe','mbappe','uefa'] },
  { id:'england', name:'England', shortName:'ENG', categoryId:'football', subCategoryId:'teams', emoji:'🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    stats:{ fifa_rank:5, wc_titles:1, wc_appearances:16, win_rate_pct:52, avg_goals_per_game:1.7, avg_goals_conceded:1.0, unbeaten_streak:8, squad_avg_age:26.1, squad_market_value_m:1050, wc_finals_appearances:1, continental_titles:1, team_trophies_total:2, wc_golden_boots:3, pressing_intensity:8, tactical_flexibility:8, player_synergy:8, youth_development:8, coach_rating:7, wc_knockout_win_rate_pct:52, penalty_shootout_wins:2, wc_clean_sheets:36, biggest_win_margin:8, global_fan_base_m:750, social_media_m:165 },
    meta:{ confederation:'UEFA', coach:'Lee Carsley', wc_best:'Winners', form:'WWDWW', key_players:'H. Kane, J. Bellingham, B. Saka, P. Foden' },
    tags:['england','eng','three lions','europe','kane','bellingham','uefa'] },
  { id:'spain', name:'Spain', shortName:'ESP', categoryId:'football', subCategoryId:'teams', emoji:'🇪🇸',
    stats:{ fifa_rank:3, wc_titles:1, wc_appearances:16, win_rate_pct:60, avg_goals_per_game:1.9, avg_goals_conceded:0.7, unbeaten_streak:15, squad_avg_age:25.2, squad_market_value_m:950, wc_finals_appearances:2, continental_titles:4, team_trophies_total:6, wc_golden_boots:2, pressing_intensity:9, tactical_flexibility:9, player_synergy:9, youth_development:9, coach_rating:9, wc_knockout_win_rate_pct:65, penalty_shootout_wins:3, wc_clean_sheets:45, biggest_win_margin:8, global_fan_base_m:500, social_media_m:105 },
    meta:{ confederation:'UEFA', coach:'Luis de la Fuente', wc_best:'Winners', form:'WWWWD', key_players:'L. Yamal, Pedri, Rodri, D. Olmo' },
    tags:['spain','esp','la roja','europe','pedri','yamal','uefa'] },
  { id:'germany', name:'Germany', shortName:'GER', categoryId:'football', subCategoryId:'teams', emoji:'🇩🇪',
    stats:{ fifa_rank:13, wc_titles:4, wc_appearances:20, win_rate_pct:59, avg_goals_per_game:2.0, avg_goals_conceded:1.0, unbeaten_streak:6, squad_avg_age:25.9, squad_market_value_m:880, wc_finals_appearances:8, continental_titles:4, team_trophies_total:8, wc_golden_boots:6, pressing_intensity:8, tactical_flexibility:8, player_synergy:7, youth_development:8, coach_rating:8, wc_knockout_win_rate_pct:68, penalty_shootout_wins:5, wc_clean_sheets:58, biggest_win_margin:7, global_fan_base_m:600, social_media_m:130 },
    meta:{ confederation:'UEFA', coach:'Julian Nagelsmann', wc_best:'Winners', form:'WDWWW', key_players:'J. Musiala, F. Wirtz, K. Havertz, M. ter Stegen' },
    tags:['germany','ger','die mannschaft','europe','ter stegen','uefa'] },
  { id:'portugal', name:'Portugal', shortName:'POR', categoryId:'football', subCategoryId:'teams', emoji:'🇵🇹',
    stats:{ fifa_rank:6, wc_titles:0, wc_appearances:9, win_rate_pct:54, avg_goals_per_game:1.8, avg_goals_conceded:0.9, unbeaten_streak:10, squad_avg_age:27.3, squad_market_value_m:750, wc_finals_appearances:0, continental_titles:2, team_trophies_total:3, wc_golden_boots:4, pressing_intensity:7, tactical_flexibility:7, player_synergy:7, youth_development:8, coach_rating:7, wc_knockout_win_rate_pct:44, penalty_shootout_wins:1, wc_clean_sheets:20, biggest_win_margin:4, global_fan_base_m:400, social_media_m:90 },
    meta:{ confederation:'UEFA', coach:'Roberto Martínez', wc_best:'Quarter-final', form:'WWWLW', key_players:'C. Ronaldo, B. Silva, R. Dias, J. Félix' },
    tags:['portugal','por','selecao','europe','ronaldo','uefa'] },
  { id:'netherlands', name:'Netherlands', shortName:'NED', categoryId:'football', subCategoryId:'teams', emoji:'🇳🇱',
    stats:{ fifa_rank:7, wc_titles:0, wc_appearances:11, win_rate_pct:52, avg_goals_per_game:1.7, avg_goals_conceded:1.0, unbeaten_streak:6, squad_avg_age:26.7, squad_market_value_m:690, wc_finals_appearances:3, continental_titles:2, team_trophies_total:3, wc_golden_boots:3, pressing_intensity:7, tactical_flexibility:8, player_synergy:7, youth_development:8, coach_rating:7, wc_knockout_win_rate_pct:52, penalty_shootout_wins:0, wc_clean_sheets:30, biggest_win_margin:5, global_fan_base_m:200, social_media_m:55 },
    meta:{ confederation:'UEFA', coach:'Ronald Koeman', wc_best:'Runner-up', form:'WWWDW', key_players:'V. van Dijk, X. Simons, C. Gakpo, T. Reijnders' },
    tags:['netherlands','ned','holland','oranje','europe','uefa'] },
  { id:'belgium', name:'Belgium', shortName:'BEL', categoryId:'football', subCategoryId:'teams', emoji:'🇧🇪',
    stats:{ fifa_rank:4, wc_titles:0, wc_appearances:14, win_rate_pct:55, avg_goals_per_game:1.8, avg_goals_conceded:0.9, unbeaten_streak:5, squad_avg_age:28.5, squad_market_value_m:760, wc_finals_appearances:1, continental_titles:0, team_trophies_total:1, wc_golden_boots:1, pressing_intensity:7, tactical_flexibility:7, player_synergy:7, youth_development:7, coach_rating:7, wc_knockout_win_rate_pct:50, penalty_shootout_wins:0, wc_clean_sheets:28, biggest_win_margin:5, global_fan_base_m:180, social_media_m:50 },
    meta:{ confederation:'UEFA', coach:'Domenico Tedesco', wc_best:'Quarter-final', form:'WDWWL', key_players:'K. De Bruyne, R. Lukaku, J. Doku, T. Courtois' },
    tags:['belgium','bel','red devils','europe','de bruyne','uefa'] },
  { id:'croatia', name:'Croatia', shortName:'CRO', categoryId:'football', subCategoryId:'teams', emoji:'🇭🇷',
    stats:{ fifa_rank:10, wc_titles:0, wc_appearances:7, win_rate_pct:50, avg_goals_per_game:1.5, avg_goals_conceded:1.0, unbeaten_streak:4, squad_avg_age:29.1, squad_market_value_m:310, wc_finals_appearances:2, continental_titles:0, team_trophies_total:0, wc_golden_boots:1, pressing_intensity:7, tactical_flexibility:8, player_synergy:9, youth_development:7, coach_rating:8, wc_knockout_win_rate_pct:67, penalty_shootout_wins:3, wc_clean_sheets:15, biggest_win_margin:4, global_fan_base_m:80, social_media_m:25 },
    meta:{ confederation:'UEFA', coach:'Zlatko Dalić', wc_best:'Runner-up', form:'WDLWW', key_players:'L. Modrić, M. Brozović, I. Perišić, M. Gvardiol' },
    tags:['croatia','cro','vatreni','europe','modric','uefa'] },
  { id:'switzerland', name:'Switzerland', shortName:'SUI', categoryId:'football', subCategoryId:'teams', emoji:'🇨🇭',
    stats:{ fifa_rank:12, wc_titles:0, wc_appearances:12, win_rate_pct:44, avg_goals_per_game:1.4, avg_goals_conceded:1.1, unbeaten_streak:5, squad_avg_age:27.2, squad_market_value_m:290, wc_finals_appearances:0, continental_titles:0, team_trophies_total:0, wc_golden_boots:0, pressing_intensity:7, tactical_flexibility:7, player_synergy:7, youth_development:7, coach_rating:7, wc_knockout_win_rate_pct:40, penalty_shootout_wins:1, wc_clean_sheets:18, biggest_win_margin:4, global_fan_base_m:50, social_media_m:16 },
    meta:{ confederation:'UEFA', coach:'Murat Yakin', wc_best:'Quarter-final', form:'WDWDW', key_players:'G. Xhaka, X. Shaqiri, B. Embolo, Y. Sommer' },
    tags:['switzerland','sui','nati','europe','uefa'] },
  { id:'austria', name:'Austria', shortName:'AUT', categoryId:'football', subCategoryId:'teams', emoji:'🇦🇹',
    stats:{ fifa_rank:22, wc_titles:0, wc_appearances:7, win_rate_pct:40, avg_goals_per_game:1.4, avg_goals_conceded:1.2, unbeaten_streak:6, squad_avg_age:26.4, squad_market_value_m:280, wc_finals_appearances:1, continental_titles:0, team_trophies_total:0, wc_golden_boots:1, pressing_intensity:7, tactical_flexibility:7, player_synergy:6, youth_development:7, coach_rating:8, wc_knockout_win_rate_pct:35, penalty_shootout_wins:0, wc_clean_sheets:12, biggest_win_margin:4, global_fan_base_m:45, social_media_m:14 },
    meta:{ confederation:'UEFA', coach:'Ralf Rangnick', wc_best:'Quarter-final', form:'WWWDW', key_players:'M. Arnautović, D. Alaba, C. Baumgartner, P. Laimer' },
    tags:['austria','aut','europe','uefa'] },
  { id:'denmark', name:'Denmark', shortName:'DEN', categoryId:'football', subCategoryId:'teams', emoji:'🇩🇰',
    stats:{ fifa_rank:20, wc_titles:0, wc_appearances:6, win_rate_pct:46, avg_goals_per_game:1.5, avg_goals_conceded:1.0, unbeaten_streak:4, squad_avg_age:27.0, squad_market_value_m:305, wc_finals_appearances:0, continental_titles:1, team_trophies_total:2, wc_golden_boots:1, pressing_intensity:7, tactical_flexibility:7, player_synergy:8, youth_development:7, coach_rating:7, wc_knockout_win_rate_pct:40, penalty_shootout_wins:1, wc_clean_sheets:12, biggest_win_margin:4, global_fan_base_m:70, social_media_m:22 },
    meta:{ confederation:'UEFA', coach:'Kasper Hjulmand', wc_best:'Quarter-final', form:'WDWWL', key_players:'C. Eriksen, P. Højlund, A. Dolberg, V. Andersen' },
    tags:['denmark','den','danish dynamite','europe','eriksen','uefa'] },
  { id:'turkey', name:'Turkey', shortName:'TUR', categoryId:'football', subCategoryId:'teams', emoji:'🇹🇷',
    stats:{ fifa_rank:29, wc_titles:0, wc_appearances:2, win_rate_pct:42, avg_goals_per_game:1.5, avg_goals_conceded:1.2, unbeaten_streak:5, squad_avg_age:26.8, squad_market_value_m:290, wc_finals_appearances:0, continental_titles:0, team_trophies_total:0, wc_golden_boots:0, pressing_intensity:7, tactical_flexibility:6, player_synergy:7, youth_development:6, coach_rating:7, wc_knockout_win_rate_pct:42, penalty_shootout_wins:0, wc_clean_sheets:6, biggest_win_margin:5, global_fan_base_m:90, social_media_m:30 },
    meta:{ confederation:'UEFA', coach:'Vincenzo Montella', wc_best:'Quarter-final', form:'WWWDL', key_players:'H. Çalhanoğlu, A. Güler, K. Akturkoglu, M. Demiral' },
    tags:['turkey','tur','europe','uefa'] },
  { id:'poland', name:'Poland', shortName:'POL', categoryId:'football', subCategoryId:'teams', emoji:'🇵🇱',
    stats:{ fifa_rank:26, wc_titles:0, wc_appearances:9, win_rate_pct:39, avg_goals_per_game:1.4, avg_goals_conceded:1.2, unbeaten_streak:3, squad_avg_age:28.2, squad_market_value_m:260, wc_finals_appearances:0, continental_titles:0, team_trophies_total:0, wc_golden_boots:3, pressing_intensity:6, tactical_flexibility:6, player_synergy:7, youth_development:6, coach_rating:6, wc_knockout_win_rate_pct:38, penalty_shootout_wins:0, wc_clean_sheets:14, biggest_win_margin:5, global_fan_base_m:110, social_media_m:32 },
    meta:{ confederation:'UEFA', coach:'Michał Probierz', wc_best:'Quarter-final', form:'WDLWW', key_players:'R. Lewandowski, P. Zieliński, P. Grosicki, W. Szczesny' },
    tags:['poland','pol','europe','lewandowski','uefa'] },
  { id:'ukraine', name:'Ukraine', shortName:'UKR', categoryId:'football', subCategoryId:'teams', emoji:'🇺🇦',
    stats:{ fifa_rank:24, wc_titles:0, wc_appearances:2, win_rate_pct:41, avg_goals_per_game:1.3, avg_goals_conceded:1.2, unbeaten_streak:3, squad_avg_age:26.9, squad_market_value_m:195, wc_finals_appearances:0, continental_titles:0, team_trophies_total:0, wc_golden_boots:0, pressing_intensity:7, tactical_flexibility:7, player_synergy:6, youth_development:7, coach_rating:7, wc_knockout_win_rate_pct:33, penalty_shootout_wins:0, wc_clean_sheets:6, biggest_win_margin:3, global_fan_base_m:55, social_media_m:18 },
    meta:{ confederation:'UEFA', coach:'Serhiy Rebrov', wc_best:'Quarter-final', form:'WDWWW', key_players:'M. Mudryk, O. Zinchenko, V. Tsygankov, A. Lunin' },
    tags:['ukraine','ukr','europe','uefa'] },
  { id:'serbia', name:'Serbia', shortName:'SRB', categoryId:'football', subCategoryId:'teams', emoji:'🇷🇸',
    stats:{ fifa_rank:33, wc_titles:0, wc_appearances:13, win_rate_pct:38, avg_goals_per_game:1.4, avg_goals_conceded:1.3, unbeaten_streak:3, squad_avg_age:27.6, squad_market_value_m:210, wc_finals_appearances:0, continental_titles:0, team_trophies_total:0, wc_golden_boots:1, pressing_intensity:6, tactical_flexibility:6, player_synergy:6, youth_development:6, coach_rating:6, wc_knockout_win_rate_pct:30, penalty_shootout_wins:0, wc_clean_sheets:10, biggest_win_margin:5, global_fan_base_m:45, social_media_m:14 },
    meta:{ confederation:'UEFA', coach:'Dragan Stojković', wc_best:'Quarter-final', form:'WLWDW', key_players:'A. Mitrović, S. Milinković-Savić, D. Tadić, N. Gudelj' },
    tags:['serbia','srb','europe','uefa'] },
  { id:'scotland', name:'Scotland', shortName:'SCO', categoryId:'football', subCategoryId:'teams', emoji:'🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    stats:{ fifa_rank:38, wc_titles:0, wc_appearances:8, win_rate_pct:34, avg_goals_per_game:1.2, avg_goals_conceded:1.3, unbeaten_streak:3, squad_avg_age:27.0, squad_market_value_m:145, wc_finals_appearances:0, continental_titles:0, team_trophies_total:0, wc_golden_boots:1, pressing_intensity:6, tactical_flexibility:6, player_synergy:6, youth_development:6, coach_rating:6, wc_knockout_win_rate_pct:25, penalty_shootout_wins:0, wc_clean_sheets:8, biggest_win_margin:5, global_fan_base_m:40, social_media_m:14 },
    meta:{ confederation:'UEFA', coach:'Steve Clarke', wc_best:'Group stage', form:'WLWDL', key_players:'A. Robertson, K. Tierney, J. McTominay, C. McGregor' },
    tags:['scotland','sco','europe','tartan army','uefa'] },
  { id:'morocco', name:'Morocco', shortName:'MAR', categoryId:'football', subCategoryId:'teams', emoji:'🇲🇦',
    stats:{ fifa_rank:14, wc_titles:0, wc_appearances:7, win_rate_pct:46, avg_goals_per_game:1.3, avg_goals_conceded:0.8, unbeaten_streak:8, squad_avg_age:26.5, squad_market_value_m:340, wc_finals_appearances:0, continental_titles:1, team_trophies_total:2, wc_golden_boots:0, pressing_intensity:8, tactical_flexibility:8, player_synergy:8, youth_development:7, coach_rating:9, wc_knockout_win_rate_pct:62, penalty_shootout_wins:2, wc_clean_sheets:16, biggest_win_margin:3, global_fan_base_m:180, social_media_m:50 },
    meta:{ confederation:'CAF', coach:'Walid Regragui', wc_best:'Quarter-final', form:'WWWDW', key_players:'A. Hakimi, H. Ziyech, Y. En-Nesyri, S. Amrabat' },
    tags:['morocco','mar','atlas lions','africa','caf'] },
  { id:'senegal', name:'Senegal', shortName:'SEN', categoryId:'football', subCategoryId:'teams', emoji:'🇸🇳',
    stats:{ fifa_rank:18, wc_titles:0, wc_appearances:4, win_rate_pct:43, avg_goals_per_game:1.4, avg_goals_conceded:1.0, unbeaten_streak:5, squad_avg_age:26.3, squad_market_value_m:255, wc_finals_appearances:0, continental_titles:2, team_trophies_total:2, wc_golden_boots:0, pressing_intensity:7, tactical_flexibility:7, player_synergy:7, youth_development:7, coach_rating:7, wc_knockout_win_rate_pct:42, penalty_shootout_wins:2, wc_clean_sheets:10, biggest_win_margin:3, global_fan_base_m:65, social_media_m:22 },
    meta:{ confederation:'CAF', coach:'Aliou Cissé', wc_best:'Quarter-final', form:'WWDWW', key_players:'S. Mané, I. Sarr, E. Mendy, K. Koulibaly' },
    tags:['senegal','sen','lions of teranga','africa','mane','caf'] },
  { id:'nigeria', name:'Nigeria', shortName:'NGA', categoryId:'football', subCategoryId:'teams', emoji:'🇳🇬',
    stats:{ fifa_rank:40, wc_titles:0, wc_appearances:7, win_rate_pct:38, avg_goals_per_game:1.4, avg_goals_conceded:1.3, unbeaten_streak:4, squad_avg_age:25.8, squad_market_value_m:185, wc_finals_appearances:0, continental_titles:3, team_trophies_total:3, wc_golden_boots:0, pressing_intensity:7, tactical_flexibility:6, player_synergy:6, youth_development:7, coach_rating:6, wc_knockout_win_rate_pct:33, penalty_shootout_wins:0, wc_clean_sheets:8, biggest_win_margin:3, global_fan_base_m:140, social_media_m:45 },
    meta:{ confederation:'CAF', coach:'Eric Chelle', wc_best:'Round of 16', form:'WWDLW', key_players:'V. Osimhen, A. Iwobi, C. Troost-Ekong, A. Lookman' },
    tags:['nigeria','nga','super eagles','africa','osimhen','caf'] },
  { id:'egypt', name:'Egypt', shortName:'EGY', categoryId:'football', subCategoryId:'teams', emoji:'🇪🇬',
    stats:{ fifa_rank:35, wc_titles:0, wc_appearances:3, win_rate_pct:36, avg_goals_per_game:1.2, avg_goals_conceded:1.1, unbeaten_streak:4, squad_avg_age:27.1, squad_market_value_m:145, wc_finals_appearances:0, continental_titles:7, team_trophies_total:8, wc_golden_boots:0, pressing_intensity:6, tactical_flexibility:6, player_synergy:7, youth_development:6, coach_rating:6, wc_knockout_win_rate_pct:20, penalty_shootout_wins:0, wc_clean_sheets:4, biggest_win_margin:3, global_fan_base_m:100, social_media_m:35 },
    meta:{ confederation:'CAF', coach:'Hossam Hassan', wc_best:'Group stage', form:'WWDWL', key_players:'M. Salah, O. Kamal, T. Mohamed, M. El-Shenawy' },
    tags:['egypt','egy','pharaohs','africa','salah','caf'] },
  { id:'south-africa', name:'South Africa', shortName:'RSA', categoryId:'football', subCategoryId:'teams', emoji:'🇿🇦',
    stats:{ fifa_rank:57, wc_titles:0, wc_appearances:3, win_rate_pct:30, avg_goals_per_game:1.0, avg_goals_conceded:1.3, unbeaten_streak:2, squad_avg_age:26.5, squad_market_value_m:80, wc_finals_appearances:0, continental_titles:3, team_trophies_total:3, wc_golden_boots:0, pressing_intensity:5, tactical_flexibility:5, player_synergy:5, youth_development:5, coach_rating:6, wc_knockout_win_rate_pct:0, penalty_shootout_wins:0, wc_clean_sheets:2, biggest_win_margin:2, global_fan_base_m:30, social_media_m:12 },
    meta:{ confederation:'CAF', coach:'Hugo Broos', wc_best:'Group stage', form:'WDLWW', key_players:'P. Tau, S. Bidvest, L. Dolly, R. de Reuck' },
    tags:['south africa','rsa','bafana bafana','africa','caf'] },
  { id:'cameroon', name:'Cameroon', shortName:'CMR', categoryId:'football', subCategoryId:'teams', emoji:'🇨🇲',
    stats:{ fifa_rank:43, wc_titles:0, wc_appearances:9, win_rate_pct:33, avg_goals_per_game:1.2, avg_goals_conceded:1.3, unbeaten_streak:3, squad_avg_age:26.7, squad_market_value_m:110, wc_finals_appearances:0, continental_titles:5, team_trophies_total:5, wc_golden_boots:0, pressing_intensity:6, tactical_flexibility:6, player_synergy:6, youth_development:6, coach_rating:6, wc_knockout_win_rate_pct:22, penalty_shootout_wins:0, wc_clean_sheets:10, biggest_win_margin:4, global_fan_base_m:50, social_media_m:16 },
    meta:{ confederation:'CAF', coach:'Marc Brys', wc_best:'Quarter-final', form:'WDWLW', key_players:'V. Aboubakar, A. Onana, K. Toko Ekambi, M. Ngadeu' },
    tags:['cameroon','cmr','indomitable lions','africa','caf'] },
  { id:'ivory-coast', name:'Ivory Coast', shortName:'CIV', categoryId:'football', subCategoryId:'teams', emoji:'🇨🇮',
    stats:{ fifa_rank:48, wc_titles:0, wc_appearances:3, win_rate_pct:35, avg_goals_per_game:1.3, avg_goals_conceded:1.2, unbeaten_streak:6, squad_avg_age:26.0, squad_market_value_m:120, wc_finals_appearances:0, continental_titles:3, team_trophies_total:3, wc_golden_boots:0, pressing_intensity:6, tactical_flexibility:6, player_synergy:6, youth_development:6, coach_rating:7, wc_knockout_win_rate_pct:17, penalty_shootout_wins:0, wc_clean_sheets:4, biggest_win_margin:3, global_fan_base_m:45, social_media_m:16 },
    meta:{ confederation:'CAF', coach:'Emerse Faé', wc_best:'Group stage', form:'WWWDW', key_players:'S. Haller, F. Koné, I. Sangaré, S. Fofana' },
    tags:['ivory coast','civ','cote divoire','elephants','africa','caf'] },
  { id:'ghana', name:'Ghana', shortName:'GHA', categoryId:'football', subCategoryId:'teams', emoji:'🇬🇭',
    stats:{ fifa_rank:61, wc_titles:0, wc_appearances:4, win_rate_pct:34, avg_goals_per_game:1.2, avg_goals_conceded:1.3, unbeaten_streak:2, squad_avg_age:25.5, squad_market_value_m:95, wc_finals_appearances:0, continental_titles:4, team_trophies_total:4, wc_golden_boots:0, pressing_intensity:6, tactical_flexibility:6, player_synergy:6, youth_development:6, coach_rating:6, wc_knockout_win_rate_pct:30, penalty_shootout_wins:0, wc_clean_sheets:7, biggest_win_margin:4, global_fan_base_m:40, social_media_m:14 },
    meta:{ confederation:'CAF', coach:'Otto Addo', wc_best:'Quarter-final', form:'WDWLW', key_players:'A. Ayew, T. Partey, M. Kudus, J. Mensah' },
    tags:['ghana','gha','black stars','africa','caf'] },
  { id:'algeria', name:'Algeria', shortName:'ALG', categoryId:'football', subCategoryId:'teams', emoji:'🇩🇿',
    stats:{ fifa_rank:52, wc_titles:0, wc_appearances:4, win_rate_pct:36, avg_goals_per_game:1.2, avg_goals_conceded:1.2, unbeaten_streak:3, squad_avg_age:26.2, squad_market_value_m:100, wc_finals_appearances:0, continental_titles:2, team_trophies_total:2, wc_golden_boots:0, pressing_intensity:6, tactical_flexibility:6, player_synergy:6, youth_development:6, coach_rating:6, wc_knockout_win_rate_pct:25, penalty_shootout_wins:0, wc_clean_sheets:6, biggest_win_margin:3, global_fan_base_m:55, social_media_m:18 },
    meta:{ confederation:'CAF', coach:'Vladimir Petkovic', wc_best:'Round of 16', form:'WDWDW', key_players:'R. Mahrez, Y. Benrahma, I. Bennacer, M. Feghouli' },
    tags:['algeria','alg','desert foxes','africa','caf'] },
  { id:'japan', name:'Japan', shortName:'JPN', categoryId:'football', subCategoryId:'teams', emoji:'🇯🇵',
    stats:{ fifa_rank:15, wc_titles:0, wc_appearances:8, win_rate_pct:46, avg_goals_per_game:1.5, avg_goals_conceded:1.0, unbeaten_streak:6, squad_avg_age:26.0, squad_market_value_m:265, wc_finals_appearances:0, continental_titles:4, team_trophies_total:4, wc_golden_boots:0, pressing_intensity:8, tactical_flexibility:8, player_synergy:8, youth_development:8, coach_rating:7, wc_knockout_win_rate_pct:38, penalty_shootout_wins:0, wc_clean_sheets:16, biggest_win_margin:4, global_fan_base_m:130, social_media_m:45 },
    meta:{ confederation:'AFC', coach:'Hajime Moriyasu', wc_best:'Round of 16', form:'WWWWW', key_players:'D. Mitoma, T. Endo, H. Kubo, S. Maeda' },
    tags:['japan','jpn','samurai blue','asia','afc'] },
  { id:'south-korea', name:'South Korea', shortName:'KOR', categoryId:'football', subCategoryId:'teams', emoji:'🇰🇷',
    stats:{ fifa_rank:23, wc_titles:0, wc_appearances:11, win_rate_pct:38, avg_goals_per_game:1.3, avg_goals_conceded:1.2, unbeaten_streak:4, squad_avg_age:26.4, squad_market_value_m:175, wc_finals_appearances:0, continental_titles:2, team_trophies_total:2, wc_golden_boots:0, pressing_intensity:7, tactical_flexibility:7, player_synergy:7, youth_development:7, coach_rating:6, wc_knockout_win_rate_pct:42, penalty_shootout_wins:2, wc_clean_sheets:14, biggest_win_margin:4, global_fan_base_m:90, social_media_m:32 },
    meta:{ confederation:'AFC', coach:'Hong Myung-bo', wc_best:'Quarter-final', form:'WWDLW', key_players:'H. Son, L. Kang-in, K. Min-jae, C. Gue-sung' },
    tags:['south korea','kor','taegeuk warriors','asia','son','afc'] },
  { id:'iran', name:'Iran', shortName:'IRN', categoryId:'football', subCategoryId:'teams', emoji:'🇮🇷',
    stats:{ fifa_rank:22, wc_titles:0, wc_appearances:6, win_rate_pct:40, avg_goals_per_game:1.3, avg_goals_conceded:1.1, unbeaten_streak:5, squad_avg_age:27.3, squad_market_value_m:135, wc_finals_appearances:0, continental_titles:3, team_trophies_total:3, wc_golden_boots:0, pressing_intensity:6, tactical_flexibility:6, player_synergy:6, youth_development:6, coach_rating:6, wc_knockout_win_rate_pct:17, penalty_shootout_wins:0, wc_clean_sheets:6, biggest_win_margin:4, global_fan_base_m:70, social_media_m:22 },
    meta:{ confederation:'AFC', coach:'Amir Ghalenoei', wc_best:'Group stage', form:'WWDWL', key_players:'M. Taremi, A. Jahanbakhsh, S. Hosseini, A. Ansarifard' },
    tags:['iran','irn','team melli','asia','afc'] },
  { id:'australia', name:'Australia', shortName:'AUS', categoryId:'football', subCategoryId:'teams', emoji:'🇦🇺',
    stats:{ fifa_rank:25, wc_titles:0, wc_appearances:6, win_rate_pct:36, avg_goals_per_game:1.2, avg_goals_conceded:1.2, unbeaten_streak:3, squad_avg_age:27.1, squad_market_value_m:150, wc_finals_appearances:0, continental_titles:0, team_trophies_total:1, wc_golden_boots:0, pressing_intensity:6, tactical_flexibility:7, player_synergy:6, youth_development:6, coach_rating:7, wc_knockout_win_rate_pct:33, penalty_shootout_wins:1, wc_clean_sheets:8, biggest_win_margin:3, global_fan_base_m:40, social_media_m:14 },
    meta:{ confederation:'AFC', coach:'Tony Popovic', wc_best:'Round of 16', form:'WDWLW', key_players:'M. Leckie, B. Irvine, J. Ramsay, A. Hrustic' },
    tags:['australia','aus','socceroos','asia','afc'] },
  { id:'saudi-arabia', name:'Saudi Arabia', shortName:'KSA', categoryId:'football', subCategoryId:'teams', emoji:'🇸🇦',
    stats:{ fifa_rank:56, wc_titles:0, wc_appearances:6, win_rate_pct:29, avg_goals_per_game:1.1, avg_goals_conceded:1.4, unbeaten_streak:3, squad_avg_age:26.8, squad_market_value_m:105, wc_finals_appearances:0, continental_titles:3, team_trophies_total:4, wc_golden_boots:0, pressing_intensity:5, tactical_flexibility:6, player_synergy:6, youth_development:5, coach_rating:6, wc_knockout_win_rate_pct:20, penalty_shootout_wins:0, wc_clean_sheets:4, biggest_win_margin:4, global_fan_base_m:50, social_media_m:18 },
    meta:{ confederation:'AFC', coach:'Roberto Mancini', wc_best:'Round of 16', form:'WDLWW', key_players:'S. Al-Dawsari, F. Al-Brikan, A. Al-Ammari, M. Al-Owais' },
    tags:['saudi arabia','ksa','green falcons','asia','afc'] },
  { id:'qatar', name:'Qatar', shortName:'QAT', categoryId:'football', subCategoryId:'teams', emoji:'🇶🇦',
    stats:{ fifa_rank:37, wc_titles:0, wc_appearances:1, win_rate_pct:31, avg_goals_per_game:1.1, avg_goals_conceded:1.5, unbeaten_streak:2, squad_avg_age:26.2, squad_market_value_m:90, wc_finals_appearances:0, continental_titles:1, team_trophies_total:1, wc_golden_boots:0, pressing_intensity:5, tactical_flexibility:5, player_synergy:5, youth_development:6, coach_rating:5, wc_knockout_win_rate_pct:0, penalty_shootout_wins:0, wc_clean_sheets:0, biggest_win_margin:2, global_fan_base_m:35, social_media_m:14 },
    meta:{ confederation:'AFC', coach:'Marquez Lopez', wc_best:'Group stage', form:'WDWWL', key_players:'A. Al-Haydos, A. Afif, M. Muntari, B. Al-Hassan' },
    tags:['qatar','qat','maroons','asia','afc'] },
  { id:'iraq', name:'Iraq', shortName:'IRQ', categoryId:'football', subCategoryId:'teams', emoji:'🇮🇶',
    stats:{ fifa_rank:63, wc_titles:0, wc_appearances:1, win_rate_pct:33, avg_goals_per_game:1.2, avg_goals_conceded:1.3, unbeaten_streak:4, squad_avg_age:25.6, squad_market_value_m:65, wc_finals_appearances:0, continental_titles:1, team_trophies_total:1, wc_golden_boots:0, pressing_intensity:5, tactical_flexibility:5, player_synergy:5, youth_development:5, coach_rating:5, wc_knockout_win_rate_pct:0, penalty_shootout_wins:0, wc_clean_sheets:0, biggest_win_margin:3, global_fan_base_m:30, social_media_m:12 },
    meta:{ confederation:'AFC', coach:'Jesús Casas', wc_best:'Group stage', form:'WWDWW', key_players:'A. Mohanad, M. Al-Tamari, A. Karrar, O. Al-Haydari' },
    tags:['iraq','irq','lions of mesopotamia','asia','afc'] },
  { id:'uzbekistan', name:'Uzbekistan', shortName:'UZB', categoryId:'football', subCategoryId:'teams', emoji:'🇺🇿',
    stats:{ fifa_rank:67, wc_titles:0, wc_appearances:0, win_rate_pct:31, avg_goals_per_game:1.1, avg_goals_conceded:1.3, unbeaten_streak:3, squad_avg_age:24.9, squad_market_value_m:55, wc_finals_appearances:0, continental_titles:0, team_trophies_total:0, wc_golden_boots:0, pressing_intensity:5, tactical_flexibility:5, player_synergy:5, youth_development:6, coach_rating:5, wc_knockout_win_rate_pct:0, penalty_shootout_wins:0, wc_clean_sheets:0, biggest_win_margin:2, global_fan_base_m:20, social_media_m:8 },
    meta:{ confederation:'AFC', coach:'Srecko Katanec', wc_best:'Group stage', form:'WWWLW', key_players:'E. Shomurodov, O. Toshmatov, J. Kholmatov, O. Alijonov' },
    tags:['uzbekistan','uzb','white wolves','asia','afc'] },
  { id:'usa', name:'USA', shortName:'USA', categoryId:'football', subCategoryId:'teams', emoji:'🇺🇸',
    stats:{ fifa_rank:16, wc_titles:0, wc_appearances:12, win_rate_pct:44, avg_goals_per_game:1.5, avg_goals_conceded:1.1, unbeaten_streak:5, squad_avg_age:25.3, squad_market_value_m:480, wc_finals_appearances:0, continental_titles:7, team_trophies_total:8, wc_golden_boots:0, pressing_intensity:7, tactical_flexibility:8, player_synergy:7, youth_development:8, coach_rating:8, wc_knockout_win_rate_pct:40, penalty_shootout_wins:1, wc_clean_sheets:20, biggest_win_margin:5, global_fan_base_m:400, social_media_m:100 },
    meta:{ confederation:'CONCACAF', coach:'Mauricio Pochettino', wc_best:'Quarter-final', form:'WDLWW', key_players:'C. Pulisic, W. McKennie, T. Adams, M. Reyna' },
    tags:['usa','united states','us soccer','pulisic','north america','concacaf','host'] },
  { id:'mexico', name:'Mexico', shortName:'MEX', categoryId:'football', subCategoryId:'teams', emoji:'🇲🇽',
    stats:{ fifa_rank:17, wc_titles:0, wc_appearances:17, win_rate_pct:45, avg_goals_per_game:1.5, avg_goals_conceded:1.2, unbeaten_streak:4, squad_avg_age:26.6, squad_market_value_m:295, wc_finals_appearances:0, continental_titles:10, team_trophies_total:12, wc_golden_boots:0, pressing_intensity:7, tactical_flexibility:7, player_synergy:7, youth_development:7, coach_rating:7, wc_knockout_win_rate_pct:33, penalty_shootout_wins:0, wc_clean_sheets:24, biggest_win_margin:5, global_fan_base_m:350, social_media_m:85 },
    meta:{ confederation:'CONCACAF', coach:'Javier Aguirre', wc_best:'Quarter-final', form:'WDWLW', key_players:'H. Lozano, S. Córdova, A. Guardado, O. Pineda' },
    tags:['mexico','mex','el tri','north america','concacaf','host'] },
  { id:'canada', name:'Canada', shortName:'CAN', categoryId:'football', subCategoryId:'teams', emoji:'🇨🇦',
    stats:{ fifa_rank:47, wc_titles:0, wc_appearances:2, win_rate_pct:38, avg_goals_per_game:1.4, avg_goals_conceded:1.2, unbeaten_streak:3, squad_avg_age:25.1, squad_market_value_m:230, wc_finals_appearances:0, continental_titles:0, team_trophies_total:0, wc_golden_boots:0, pressing_intensity:6, tactical_flexibility:7, player_synergy:7, youth_development:8, coach_rating:7, wc_knockout_win_rate_pct:0, penalty_shootout_wins:0, wc_clean_sheets:2, biggest_win_margin:3, global_fan_base_m:60, social_media_m:22 },
    meta:{ confederation:'CONCACAF', coach:'Jesse Marsch', wc_best:'Group stage', form:'WWDWW', key_players:'A. Davies, J. David, O. Kossounou, T. Hoilett' },
    tags:['canada','can','north america','concacaf','host','davies'] },
  { id:'costa-rica', name:'Costa Rica', shortName:'CRC', categoryId:'football', subCategoryId:'teams', emoji:'🇨🇷',
    stats:{ fifa_rank:53, wc_titles:0, wc_appearances:6, win_rate_pct:34, avg_goals_per_game:1.1, avg_goals_conceded:1.2, unbeaten_streak:2, squad_avg_age:27.5, squad_market_value_m:75, wc_finals_appearances:0, continental_titles:3, team_trophies_total:4, wc_golden_boots:0, pressing_intensity:6, tactical_flexibility:7, player_synergy:7, youth_development:6, coach_rating:6, wc_knockout_win_rate_pct:50, penalty_shootout_wins:2, wc_clean_sheets:12, biggest_win_margin:4, global_fan_base_m:30, social_media_m:12 },
    meta:{ confederation:'CONCACAF', coach:'Gustavo Alfaro', wc_best:'Quarter-final', form:'WDWLW', key_players:'K. Fuller, C. Borges, B. Ruiz, P. Wanchope' },
    tags:['costa rica','crc','sele','north america','concacaf'] },
  { id:'panama', name:'Panama', shortName:'PAN', categoryId:'football', subCategoryId:'teams', emoji:'🇵🇦',
    stats:{ fifa_rank:78, wc_titles:0, wc_appearances:2, win_rate_pct:28, avg_goals_per_game:0.9, avg_goals_conceded:1.4, unbeaten_streak:2, squad_avg_age:27.2, squad_market_value_m:45, wc_finals_appearances:0, continental_titles:1, team_trophies_total:1, wc_golden_boots:0, pressing_intensity:5, tactical_flexibility:5, player_synergy:5, youth_development:5, coach_rating:5, wc_knockout_win_rate_pct:0, penalty_shootout_wins:0, wc_clean_sheets:0, biggest_win_margin:2, global_fan_base_m:15, social_media_m:6 },
    meta:{ confederation:'CONCACAF', coach:'Thomas Christiansen', wc_best:'Group stage', form:'WDLLW', key_players:'M. Fajardo, A. Torres, E. Davis, R. Murillo' },
    tags:['panama','pan','canaleros','north america','concacaf'] },
  { id:'jamaica', name:'Jamaica', shortName:'JAM', categoryId:'football', subCategoryId:'teams', emoji:'🇯🇲',
    stats:{ fifa_rank:70, wc_titles:0, wc_appearances:1, win_rate_pct:30, avg_goals_per_game:1.0, avg_goals_conceded:1.4, unbeaten_streak:2, squad_avg_age:25.8, squad_market_value_m:55, wc_finals_appearances:0, continental_titles:0, team_trophies_total:0, wc_golden_boots:0, pressing_intensity:5, tactical_flexibility:5, player_synergy:5, youth_development:5, coach_rating:5, wc_knockout_win_rate_pct:0, penalty_shootout_wins:0, wc_clean_sheets:0, biggest_win_margin:1, global_fan_base_m:20, social_media_m:8 },
    meta:{ confederation:'CONCACAF', coach:'Steve McClaren', wc_best:'Group stage', form:'WDWLW', key_players:'D. Antonio, L. Bailey, K. Anderson, N. Nicholson' },
    tags:['jamaica','jam','reggae boyz','north america','concacaf'] },
  { id:'new-zealand', name:'New Zealand', shortName:'NZL', categoryId:'football', subCategoryId:'teams', emoji:'🇳🇿',
    stats:{ fifa_rank:95, wc_titles:0, wc_appearances:3, win_rate_pct:22, avg_goals_per_game:0.8, avg_goals_conceded:1.7, unbeaten_streak:1, squad_avg_age:26.1, squad_market_value_m:30, wc_finals_appearances:0, continental_titles:4, team_trophies_total:4, wc_golden_boots:0, pressing_intensity:4, tactical_flexibility:5, player_synergy:4, youth_development:5, coach_rating:5, wc_knockout_win_rate_pct:0, penalty_shootout_wins:0, wc_clean_sheets:2, biggest_win_margin:2, global_fan_base_m:15, social_media_m:6 },
    meta:{ confederation:'OFC', coach:'Darren Bazeley', wc_best:'Group stage', form:'WDLLW', key_players:'C. Wood, W. Spence, L. Cacace, A. Garbett' },
    tags:['new zealand','nzl','all whites','oceania','ofc'] },
  { id:'paraguay', name:'Paraguay', shortName:'PAR', categoryId:'football', subCategoryId:'teams', emoji:'🇵🇾',
    stats:{ fifa_rank:58, wc_titles:0, wc_appearances:9, win_rate_pct:36, avg_goals_per_game:1.1, avg_goals_conceded:1.3, unbeaten_streak:2, squad_avg_age:26.3, squad_market_value_m:90, wc_finals_appearances:0, continental_titles:2, team_trophies_total:2, wc_golden_boots:1, pressing_intensity:6, tactical_flexibility:6, player_synergy:6, youth_development:6, coach_rating:6, wc_knockout_win_rate_pct:40, penalty_shootout_wins:2, wc_clean_sheets:14, biggest_win_margin:4, global_fan_base_m:30, social_media_m:12 },
    meta:{ confederation:'CONMEBOL', coach:'Gustavo Alfaro', wc_best:'Quarter-final', form:'WDWLW', key_players:'M. Almiron, R. Sanabria, J. Enciso, A. Cubas' },
    tags:['paraguay','par','guarania','south america','conmebol'] },
  { id:'romania', name:'Romania', shortName:'ROU', categoryId:'football', subCategoryId:'teams', emoji:'🇷🇴',
    stats:{ fifa_rank:46, wc_titles:0, wc_appearances:8, win_rate_pct:36, avg_goals_per_game:1.2, avg_goals_conceded:1.3, unbeaten_streak:4, squad_avg_age:26.0, squad_market_value_m:115, wc_finals_appearances:1, continental_titles:0, team_trophies_total:1, wc_golden_boots:1, pressing_intensity:6, tactical_flexibility:6, player_synergy:6, youth_development:6, coach_rating:7, wc_knockout_win_rate_pct:38, penalty_shootout_wins:1, wc_clean_sheets:12, biggest_win_margin:4, global_fan_base_m:45, social_media_m:16 },
    meta:{ confederation:'UEFA', coach:'Mircea Lucescu', wc_best:'Quarter-final', form:'WWDWL', key_players:'N. Stanciu, R. Marin, D. Man, F. Drăguș' },
    tags:['romania','rou','tricolorii','europe','uefa'] },
];

const PLAYERS = [
  { id:'messi', name:'Lionel Messi', shortName:'Messi', categoryId:'football', subCategoryId:'players', emoji:'🇦🇷',
    stats:{ age:38, goals_international:112, assists_international:56, wc_goals:13, player_wc_titles:1, career_club_goals:706, ballon_dor:8, ucl_titles:4, peak_rating:99, current_rating:90, pace:85, shooting:95, passing:96, dribbling:99, defending:40, physicality:65, creativity:99, big_game_goals:23, conversion_rate_pct:22, hat_tricks:10, player_trophies_total:44, market_value_m:35, goals_per_game:0.82, intl_caps:191, free_kick_goals:65, penalty_record_pct:78 },
    meta:{ position:'Forward', club:'Inter Miami', nationality:'Argentina', form:'WWWDW', key_stat:"8× Ballon d'Or · 2022 World Cup winner" },
    tags:['messi','leo messi','goat','argentina','inter miami','forward','ballon dor'] },
  { id:'ronaldo', name:'Cristiano Ronaldo', shortName:'Ronaldo', categoryId:'football', subCategoryId:'players', emoji:'🇵🇹',
    stats:{ age:41, goals_international:130, assists_international:43, wc_goals:8, player_wc_titles:0, career_club_goals:895, ballon_dor:5, ucl_titles:5, peak_rating:97, current_rating:82, pace:80, shooting:97, passing:79, dribbling:88, defending:35, physicality:78, creativity:84, big_game_goals:18, conversion_rate_pct:23, hat_tricks:10, player_trophies_total:34, market_value_m:20, goals_per_game:0.69, intl_caps:219, free_kick_goals:58, penalty_record_pct:87 },
    meta:{ position:'Forward', club:'Al Nassr', nationality:'Portugal', form:'WWWLW', key_stat:'All-time leading international scorer (130 goals)' },
    tags:['ronaldo','cr7','cristiano','goat','portugal','al nassr','forward'] },
  { id:'mbappe', name:'Kylian Mbappé', shortName:'Mbappé', categoryId:'football', subCategoryId:'players', emoji:'🇫🇷',
    stats:{ age:27, goals_international:52, assists_international:28, wc_goals:12, player_wc_titles:1, career_club_goals:310, ballon_dor:0, ucl_titles:1, peak_rating:94, current_rating:94, pace:99, shooting:92, passing:83, dribbling:94, defending:38, physicality:77, creativity:88, big_game_goals:18, conversion_rate_pct:28, hat_tricks:5, player_trophies_total:20, market_value_m:180, goals_per_game:0.72, intl_caps:87, free_kick_goals:6, penalty_record_pct:88 },
    meta:{ position:'Forward', club:'Real Madrid', nationality:'France', form:'WWWWW', key_stat:'2018 WC winner · 12 World Cup goals at age 27' },
    tags:['mbappe','kylian','france','real madrid','forward','pace'] },
  { id:'haaland', name:'Erling Haaland', shortName:'Haaland', categoryId:'football', subCategoryId:'players', emoji:'🇳🇴',
    stats:{ age:25, goals_international:34, assists_international:9, wc_goals:0, player_wc_titles:0, career_club_goals:258, ballon_dor:1, ucl_titles:1, peak_rating:93, current_rating:93, pace:90, shooting:96, passing:62, dribbling:75, defending:45, physicality:88, creativity:70, big_game_goals:12, conversion_rate_pct:42, hat_tricks:9, player_trophies_total:12, market_value_m:200, goals_per_game:0.85, intl_caps:50, free_kick_goals:2, penalty_record_pct:91 },
    meta:{ position:'Forward', club:'Manchester City', nationality:'Norway', form:'WWWDW', key_stat:"258 career club goals · 2023 UCL & Ballon d'Or winner" },
    tags:['haaland','erling','norway','manchester city','forward','striker'] },
  { id:'vinicius', name:'Vinicius Jr.', shortName:'Vinicius', categoryId:'football', subCategoryId:'players', emoji:'🇧🇷',
    stats:{ age:24, goals_international:28, assists_international:20, wc_goals:2, player_wc_titles:0, career_club_goals:165, ballon_dor:1, ucl_titles:2, peak_rating:92, current_rating:92, pace:97, shooting:84, passing:80, dribbling:96, defending:35, physicality:70, creativity:90, big_game_goals:10, conversion_rate_pct:24, hat_tricks:2, player_trophies_total:10, market_value_m:220, goals_per_game:0.72, intl_caps:65, free_kick_goals:4, penalty_record_pct:83 },
    meta:{ position:'Forward', club:'Real Madrid', nationality:'Brazil', form:'WWWWW', key_stat:"2× UCL winner · 2024 Ballon d'Or runner-up" },
    tags:['vinicius','vini jr','brazil','real madrid','forward','winger'] },
  { id:'pedri', name:'Pedri', shortName:'Pedri', categoryId:'football', subCategoryId:'players', emoji:'🇪🇸',
    stats:{ age:23, goals_international:12, assists_international:15, wc_goals:1, player_wc_titles:0, career_club_goals:55, ballon_dor:0, ucl_titles:0, peak_rating:89, current_rating:89, pace:75, shooting:72, passing:90, dribbling:90, defending:68, physicality:65, creativity:92, big_game_goals:4, conversion_rate_pct:15, hat_tricks:0, player_trophies_total:8, market_value_m:90, goals_per_game:0.18, intl_caps:75, free_kick_goals:2, penalty_record_pct:70 },
    meta:{ position:'Midfielder', club:'Barcelona', nationality:'Spain', form:'WWWDW', key_stat:"Euro 2024 winner · Spain's creative heartbeat" },
    tags:['pedri','spain','barcelona','midfielder','creative'] },
  { id:'bellingham', name:'Jude Bellingham', shortName:'Bellingham', categoryId:'football', subCategoryId:'players', emoji:'🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    stats:{ age:22, goals_international:18, assists_international:12, wc_goals:3, player_wc_titles:0, career_club_goals:95, ballon_dor:0, ucl_titles:1, peak_rating:91, current_rating:91, pace:82, shooting:85, passing:86, dribbling:87, defending:75, physicality:82, creativity:88, big_game_goals:8, conversion_rate_pct:20, hat_tricks:1, player_trophies_total:5, market_value_m:180, goals_per_game:0.26, intl_caps:75, free_kick_goals:3, penalty_record_pct:75 },
    meta:{ position:'Midfielder', club:'Real Madrid', nationality:'England', form:'WWWWW', key_stat:'2024 UCL winner · 18 international goals by 22' },
    tags:['bellingham','jude','england','real madrid','midfielder'] },
  { id:'salah', name:'Mohamed Salah', shortName:'Salah', categoryId:'football', subCategoryId:'players', emoji:'🇪🇬',
    stats:{ age:33, goals_international:57, assists_international:31, wc_goals:0, player_wc_titles:0, career_club_goals:360, ballon_dor:0, ucl_titles:1, peak_rating:94, current_rating:88, pace:90, shooting:90, passing:80, dribbling:90, defending:45, physicality:72, creativity:85, big_game_goals:14, conversion_rate_pct:26, hat_tricks:6, player_trophies_total:15, market_value_m:50, goals_per_game:0.52, intl_caps:110, free_kick_goals:8, penalty_record_pct:85 },
    meta:{ position:'Forward', club:'Liverpool', nationality:'Egypt', form:'WWWDW', key_stat:'57 international goals · 4× PL Golden Boot' },
    tags:['salah','mo salah','egypt','liverpool','forward','winger'] },
  { id:'kane', name:'Harry Kane', shortName:'Kane', categoryId:'football', subCategoryId:'players', emoji:'🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    stats:{ age:32, goals_international:69, assists_international:18, wc_goals:6, player_wc_titles:0, career_club_goals:370, ballon_dor:0, ucl_titles:0, peak_rating:92, current_rating:88, pace:75, shooting:95, passing:82, dribbling:75, defending:40, physicality:80, creativity:78, big_game_goals:15, conversion_rate_pct:27, hat_tricks:8, player_trophies_total:3, market_value_m:90, goals_per_game:0.68, intl_caps:108, free_kick_goals:5, penalty_record_pct:89 },
    meta:{ position:'Forward', club:'Bayern Munich', nationality:'England', form:'WWWWW', key_stat:'69 international goals · 2023 WC Golden Boot' },
    tags:['kane','harry kane','england','bayern munich','striker','golden boot'] },
  { id:'modric', name:'Luka Modrić', shortName:'Modrić', categoryId:'football', subCategoryId:'players', emoji:'🇭🇷',
    stats:{ age:40, goals_international:24, assists_international:32, wc_goals:2, player_wc_titles:0, career_club_goals:115, ballon_dor:1, ucl_titles:6, peak_rating:97, current_rating:80, pace:72, shooting:72, passing:93, dribbling:91, defending:72, physicality:62, creativity:93, big_game_goals:5, conversion_rate_pct:14, hat_tricks:1, player_trophies_total:22, market_value_m:5, goals_per_game:0.14, intl_caps:183, free_kick_goals:8, penalty_record_pct:72 },
    meta:{ position:'Midfielder', club:'Al Qadsiah', nationality:'Croatia', form:'WDWWL', key_stat:"2018 WC runner-up · 2018 Ballon d'Or · 6× UCL winner" },
    tags:['modric','luka','croatia','al qadsiah','midfielder','veteran','ballon dor'] },
  { id:'de-bruyne', name:'Kevin De Bruyne', shortName:'De Bruyne', categoryId:'football', subCategoryId:'players', emoji:'🇧🇪',
    stats:{ age:34, goals_international:28, assists_international:52, wc_goals:2, player_wc_titles:0, career_club_goals:165, ballon_dor:0, ucl_titles:1, peak_rating:96, current_rating:86, pace:76, shooting:83, passing:96, dribbling:87, defending:62, physicality:72, creativity:97, big_game_goals:8, conversion_rate_pct:18, hat_tricks:3, player_trophies_total:22, market_value_m:25, goals_per_game:0.19, intl_caps:104, free_kick_goals:15, penalty_record_pct:70 },
    meta:{ position:'Midfielder', club:'Manchester City', nationality:'Belgium', form:'WWDWL', key_stat:'52 international assists · 6× PL title with Man City' },
    tags:['de bruyne','kdb','kevin','belgium','manchester city','midfielder','assist king'] },
  { id:'lewandowski', name:'Robert Lewandowski', shortName:'Lewandowski', categoryId:'football', subCategoryId:'players', emoji:'🇵🇱',
    stats:{ age:37, goals_international:82, assists_international:30, wc_goals:1, player_wc_titles:0, career_club_goals:620, ballon_dor:0, ucl_titles:1, peak_rating:96, current_rating:83, pace:77, shooting:96, passing:80, dribbling:80, defending:42, physicality:80, creativity:78, big_game_goals:12, conversion_rate_pct:30, hat_tricks:10, player_trophies_total:22, market_value_m:15, goals_per_game:0.66, intl_caps:148, free_kick_goals:18, penalty_record_pct:92 },
    meta:{ position:'Forward', club:'Barcelona', nationality:'Poland', form:'WWWDW', key_stat:'82 international goals · 2021 FIFA Best Player' },
    tags:['lewandowski','lewy','robert','poland','barcelona','striker'] },
  { id:'benzema', name:'Karim Benzema', shortName:'Benzema', categoryId:'football', subCategoryId:'players', emoji:'🇫🇷',
    stats:{ age:37, goals_international:37, assists_international:26, wc_goals:0, player_wc_titles:0, career_club_goals:500, ballon_dor:1, ucl_titles:5, peak_rating:96, current_rating:78, pace:75, shooting:90, passing:80, dribbling:84, defending:45, physicality:75, creativity:85, big_game_goals:10, conversion_rate_pct:22, hat_tricks:4, player_trophies_total:26, market_value_m:8, goals_per_game:0.43, intl_caps:97, free_kick_goals:6, penalty_record_pct:79 },
    meta:{ position:'Forward', club:'Al Ittihad', nationality:'France', form:'WDWWW', key_stat:"2022 Ballon d'Or · 5× UCL winner with Real Madrid" },
    tags:['benzema','karim','france','al ittihad','striker','retired international','ballon dor'] },
  { id:'neymar', name:'Neymar Jr.', shortName:'Neymar', categoryId:'football', subCategoryId:'players', emoji:'🇧🇷',
    stats:{ age:34, goals_international:79, assists_international:56, wc_goals:8, player_wc_titles:0, career_club_goals:380, ballon_dor:0, ucl_titles:1, peak_rating:95, current_rating:78, pace:88, shooting:86, passing:83, dribbling:95, defending:30, physicality:65, creativity:93, big_game_goals:12, conversion_rate_pct:22, hat_tricks:7, player_trophies_total:20, market_value_m:25, goals_per_game:0.68, intl_caps:128, free_kick_goals:22, penalty_record_pct:82 },
    meta:{ position:'Forward', club:'Al Hilal', nationality:'Brazil', form:'WDWWL', key_stat:"79 international goals · World's most expensive player (2017)" },
    tags:['neymar','ney','brazil','al hilal','forward','winger'] },
  { id:'son', name:'Son Heung-min', shortName:'Son', categoryId:'football', subCategoryId:'players', emoji:'🇰🇷',
    stats:{ age:33, goals_international:48, assists_international:26, wc_goals:2, player_wc_titles:0, career_club_goals:245, ballon_dor:0, ucl_titles:0, peak_rating:90, current_rating:84, pace:88, shooting:88, passing:80, dribbling:88, defending:48, physicality:70, creativity:82, big_game_goals:6, conversion_rate_pct:24, hat_tricks:5, player_trophies_total:4, market_value_m:30, goals_per_game:0.44, intl_caps:127, free_kick_goals:5, penalty_record_pct:78 },
    meta:{ position:'Forward', club:'Tottenham Hotspur', nationality:'South Korea', form:'WWWDW', key_stat:"48 international goals · Asia's best-ever striker" },
    tags:['son','heung min','south korea','tottenham','forward','winger'] },
  { id:'yamal', name:'Lamine Yamal', shortName:'Yamal', categoryId:'football', subCategoryId:'players', emoji:'🇪🇸',
    stats:{ age:18, goals_international:10, assists_international:14, wc_goals:1, player_wc_titles:0, career_club_goals:38, ballon_dor:0, ucl_titles:0, peak_rating:93, current_rating:90, pace:90, shooting:80, passing:84, dribbling:92, defending:35, physicality:58, creativity:90, big_game_goals:3, conversion_rate_pct:22, hat_tricks:0, player_trophies_total:2, market_value_m:150, goals_per_game:0.29, intl_caps:35, free_kick_goals:2, penalty_record_pct:70 },
    meta:{ position:'Forward', club:'Barcelona', nationality:'Spain', form:'WWWWW', key_stat:'Euro 2024 winner at 17 · Youngest WC goal scorer' },
    tags:['yamal','lamine','spain','barcelona','forward','winger','wonderkid'] },
  { id:'saka', name:'Bukayo Saka', shortName:'Saka', categoryId:'football', subCategoryId:'players', emoji:'🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    stats:{ age:23, goals_international:22, assists_international:20, wc_goals:3, player_wc_titles:0, career_club_goals:90, ballon_dor:0, ucl_titles:0, peak_rating:89, current_rating:89, pace:84, shooting:83, passing:82, dribbling:85, defending:60, physicality:68, creativity:85, big_game_goals:5, conversion_rate_pct:24, hat_tricks:1, player_trophies_total:3, market_value_m:120, goals_per_game:0.31, intl_caps:68, free_kick_goals:3, penalty_record_pct:80 },
    meta:{ position:'Forward', club:'Arsenal', nationality:'England', form:'WWWDW', key_stat:"22 int'l goals · England's most reliable winger" },
    tags:['saka','bukayo','england','arsenal','forward','winger'] },
  { id:'rodrigo', name:'Rodri', shortName:'Rodri', categoryId:'football', subCategoryId:'players', emoji:'🇪🇸',
    stats:{ age:29, goals_international:15, assists_international:18, wc_goals:1, player_wc_titles:0, career_club_goals:60, ballon_dor:1, ucl_titles:1, peak_rating:94, current_rating:93, pace:65, shooting:72, passing:91, dribbling:82, defending:88, physicality:80, creativity:88, big_game_goals:4, conversion_rate_pct:18, hat_tricks:0, player_trophies_total:12, market_value_m:100, goals_per_game:0.15, intl_caps:85, free_kick_goals:4, penalty_record_pct:70 },
    meta:{ position:'Midfielder', club:'Manchester City', nationality:'Spain', form:'WWWWD', key_stat:"2024 Ballon d'Or · Euro 2024 winner · Best defensive MF" },
    tags:['rodri','rodrigo hernandez','spain','manchester city','midfielder','ballon dor'] },
  { id:'ruben-dias', name:'Rúben Dias', shortName:'Rúben Dias', categoryId:'football', subCategoryId:'players', emoji:'🇵🇹',
    stats:{ age:27, goals_international:5, assists_international:3, wc_goals:0, player_wc_titles:0, career_club_goals:22, ballon_dor:0, ucl_titles:1, peak_rating:91, current_rating:91, pace:72, shooting:45, passing:72, dribbling:62, defending:93, physicality:85, creativity:62, big_game_goals:1, conversion_rate_pct:10, hat_tricks:0, player_trophies_total:8, market_value_m:65, goals_per_game:0.04, intl_caps:60, free_kick_goals:0, penalty_record_pct:60 },
    meta:{ position:'Defender', club:'Manchester City', nationality:'Portugal', form:'WWWDW', key_stat:'2021 PL Player of the Year · Cornerstone of Man City defence' },
    tags:['ruben dias','dias','portugal','manchester city','defender','centre back'] },
  { id:'alisson', name:'Alisson Becker', shortName:'Alisson', categoryId:'football', subCategoryId:'players', emoji:'🇧🇷',
    stats:{ age:32, goals_international:0, assists_international:2, wc_goals:0, player_wc_titles:0, career_club_goals:0, ballon_dor:0, ucl_titles:1, peak_rating:93, current_rating:90, pace:65, shooting:20, passing:80, dribbling:55, defending:92, physicality:80, creativity:60, big_game_goals:0, conversion_rate_pct:5, hat_tricks:0, player_trophies_total:8, market_value_m:30, goals_per_game:0.01, intl_caps:80, free_kick_goals:0, penalty_record_pct:65 },
    meta:{ position:'Goalkeeper', club:'Liverpool', nationality:'Brazil', form:'WWWWW', key_stat:'2019 UCL winner · 2022 FIFA Best Goalkeeper' },
    tags:['alisson','alisson becker','brazil','liverpool','goalkeeper','gk'] },
  { id:'courtois', name:'Thibaut Courtois', shortName:'Courtois', categoryId:'football', subCategoryId:'players', emoji:'🇧🇪',
    stats:{ age:33, goals_international:0, assists_international:1, wc_goals:0, player_wc_titles:0, career_club_goals:0, ballon_dor:0, ucl_titles:2, peak_rating:95, current_rating:90, pace:62, shooting:18, passing:78, dribbling:52, defending:94, physicality:82, creativity:58, big_game_goals:0, conversion_rate_pct:4, hat_tricks:0, player_trophies_total:18, market_value_m:30, goals_per_game:0.0, intl_caps:101, free_kick_goals:0, penalty_record_pct:65 },
    meta:{ position:'Goalkeeper', club:'Real Madrid', nationality:'Belgium', form:'WWWDW', key_stat:'2022 UCL Final MVP · Best GK in 2022 WC' },
    tags:['courtois','thibaut','belgium','real madrid','goalkeeper','gk'] },
  { id:'ter-stegen', name:'Marc-André ter Stegen', shortName:'Ter Stegen', categoryId:'football', subCategoryId:'players', emoji:'🇩🇪',
    stats:{ age:33, goals_international:0, assists_international:0, wc_goals:0, player_wc_titles:0, career_club_goals:0, ballon_dor:0, ucl_titles:1, peak_rating:92, current_rating:88, pace:60, shooting:18, passing:80, dribbling:55, defending:91, physicality:78, creativity:60, big_game_goals:0, conversion_rate_pct:3, hat_tricks:0, player_trophies_total:8, market_value_m:20, goals_per_game:0.0, intl_caps:42, free_kick_goals:0, penalty_record_pct:62 },
    meta:{ position:'Goalkeeper', club:'Barcelona', nationality:'Germany', form:'WWDWW', key_stat:"Germany's #1 · Known for sweeper-keeper style" },
    tags:['ter stegen','marc andre','germany','barcelona','goalkeeper','gk'] },
  { id:'osimhen', name:'Victor Osimhen', shortName:'Osimhen', categoryId:'football', subCategoryId:'players', emoji:'🇳🇬',
    stats:{ age:26, goals_international:22, assists_international:8, wc_goals:0, player_wc_titles:0, career_club_goals:130, ballon_dor:0, ucl_titles:0, peak_rating:89, current_rating:89, pace:90, shooting:88, passing:68, dribbling:82, defending:38, physicality:82, creativity:75, big_game_goals:6, conversion_rate_pct:28, hat_tricks:3, player_trophies_total:4, market_value_m:70, goals_per_game:0.44, intl_caps:52, free_kick_goals:2, penalty_record_pct:74 },
    meta:{ position:'Forward', club:'Galatasaray', nationality:'Nigeria', form:'WWWDW', key_stat:'Top African striker · 2023 Serie A top scorer' },
    tags:['osimhen','victor','nigeria','galatasaray','striker','forward'] },
  { id:'diallo', name:'Serhou Guirassy', shortName:'Guirassy', categoryId:'football', subCategoryId:'players', emoji:'🇬🇳',
    stats:{ age:29, goals_international:16, assists_international:4, wc_goals:0, player_wc_titles:0, career_club_goals:115, ballon_dor:0, ucl_titles:0, peak_rating:86, current_rating:86, pace:82, shooting:85, passing:65, dribbling:74, defending:35, physicality:80, creativity:68, big_game_goals:3, conversion_rate_pct:26, hat_tricks:2, player_trophies_total:2, market_value_m:60, goals_per_game:0.42, intl_caps:38, free_kick_goals:2, penalty_record_pct:72 },
    meta:{ position:'Forward', club:'Borussia Dortmund', nationality:'Guinea', form:'WWWWL', key_stat:"Bundesliga top scorer 2024 · Guinea's all-time leading scorer" },
    tags:['guirassy','serhou','guinea','borussia dortmund','striker'] },
  { id:'brozovic', name:'Marcelo Brozović', shortName:'Brozović', categoryId:'football', subCategoryId:'players', emoji:'🇭🇷',
    stats:{ age:32, goals_international:12, assists_international:22, wc_goals:1, player_wc_titles:0, career_club_goals:65, ballon_dor:0, ucl_titles:0, peak_rating:88, current_rating:83, pace:70, shooting:68, passing:87, dribbling:82, defending:75, physicality:72, creativity:84, big_game_goals:4, conversion_rate_pct:12, hat_tricks:0, player_trophies_total:4, market_value_m:8, goals_per_game:0.10, intl_caps:91, free_kick_goals:4, penalty_record_pct:65 },
    meta:{ position:'Midfielder', club:'Al Nassr', nationality:'Croatia', form:'WDWWL', key_stat:"Croatia's engine in 2018 WC run to final" },
    tags:['brozovic','marcelo','croatia','al nassr','midfielder'] },
  { id:'valverde', name:'Federico Valverde', shortName:'Valverde', categoryId:'football', subCategoryId:'players', emoji:'🇺🇾',
    stats:{ age:26, goals_international:12, assists_international:10, wc_goals:1, player_wc_titles:0, career_club_goals:55, ballon_dor:0, ucl_titles:2, peak_rating:90, current_rating:90, pace:85, shooting:78, passing:84, dribbling:83, defending:77, physicality:80, creativity:82, big_game_goals:4, conversion_rate_pct:18, hat_tricks:0, player_trophies_total:8, market_value_m:90, goals_per_game:0.17, intl_caps:62, free_kick_goals:3, penalty_record_pct:72 },
    meta:{ position:'Midfielder', club:'Real Madrid', nationality:'Uruguay', form:'WWWWW', key_stat:"2× UCL winner · Uruguay's top midfielder" },
    tags:['valverde','fede','federico','uruguay','real madrid','midfielder'] },
  { id:'carvajal', name:'Dani Carvajal', shortName:'Carvajal', categoryId:'football', subCategoryId:'players', emoji:'🇪🇸',
    stats:{ age:33, goals_international:6, assists_international:14, wc_goals:1, player_wc_titles:0, career_club_goals:20, ballon_dor:0, ucl_titles:5, peak_rating:90, current_rating:85, pace:76, shooting:60, passing:77, dribbling:76, defending:86, physicality:72, creativity:72, big_game_goals:3, conversion_rate_pct:12, hat_tricks:0, player_trophies_total:18, market_value_m:30, goals_per_game:0.05, intl_caps:80, free_kick_goals:1, penalty_record_pct:65 },
    meta:{ position:'Defender', club:'Real Madrid', nationality:'Spain', form:'WWWDW', key_stat:'5× UCL winner · Euro 2024 Player of the Tournament' },
    tags:['carvajal','dani','spain','real madrid','defender','right back'] },
  { id:'chiesa', name:'Federico Chiesa', shortName:'Chiesa', categoryId:'football', subCategoryId:'players', emoji:'🇮🇹',
    stats:{ age:27, goals_international:18, assists_international:10, wc_goals:0, player_wc_titles:0, career_club_goals:85, ballon_dor:0, ucl_titles:0, peak_rating:88, current_rating:85, pace:88, shooting:80, passing:74, dribbling:82, defending:55, physicality:72, creativity:80, big_game_goals:5, conversion_rate_pct:22, hat_tricks:1, player_trophies_total:5, market_value_m:55, goals_per_game:0.25, intl_caps:73, free_kick_goals:4, penalty_record_pct:72 },
    meta:{ position:'Forward', club:'Liverpool', nationality:'Italy', form:'WWWDL', key_stat:"Euro 2020 winner · Italy's fastest winger" },
    tags:['chiesa','federico','italy','liverpool','forward','winger'] },
  { id:'frattesi', name:'Davide Frattesi', shortName:'Frattesi', categoryId:'football', subCategoryId:'players', emoji:'🇮🇹',
    stats:{ age:25, goals_international:8, assists_international:5, wc_goals:0, player_wc_titles:0, career_club_goals:55, ballon_dor:0, ucl_titles:0, peak_rating:85, current_rating:85, pace:78, shooting:76, passing:78, dribbling:78, defending:72, physicality:75, creativity:78, big_game_goals:2, conversion_rate_pct:18, hat_tricks:0, player_trophies_total:4, market_value_m:45, goals_per_game:0.19, intl_caps:40, free_kick_goals:2, penalty_record_pct:68 },
    meta:{ position:'Midfielder', club:'Inter Milan', nationality:'Italy', form:'WWWWW', key_stat:'Italy\'s top Super Sub · 8 goals from bench in 2024' },
    tags:['frattesi','davide','italy','inter milan','midfielder'] },
  { id:'doku', name:'Jérémy Doku', shortName:'Doku', categoryId:'football', subCategoryId:'players', emoji:'🇧🇪',
    stats:{ age:23, goals_international:8, assists_international:10, wc_goals:0, player_wc_titles:0, career_club_goals:45, ballon_dor:0, ucl_titles:0, peak_rating:87, current_rating:87, pace:96, shooting:74, passing:75, dribbling:90, defending:38, physicality:65, creativity:84, big_game_goals:2, conversion_rate_pct:16, hat_tricks:0, player_trophies_total:4, market_value_m:65, goals_per_game:0.19, intl_caps:40, free_kick_goals:2, penalty_record_pct:65 },
    meta:{ position:'Forward', club:'Manchester City', nationality:'Belgium', form:'WWWWW', key_stat:'Fastest dribbler in the Premier League' },
    tags:['doku','jeremy','belgium','manchester city','forward','winger'] },
  { id:'olise', name:'Michael Olise', shortName:'Olise', categoryId:'football', subCategoryId:'players', emoji:'🇫🇷',
    stats:{ age:23, goals_international:6, assists_international:6, wc_goals:0, player_wc_titles:0, career_club_goals:55, ballon_dor:0, ucl_titles:0, peak_rating:87, current_rating:87, pace:84, shooting:80, passing:80, dribbling:86, defending:45, physicality:65, creativity:86, big_game_goals:2, conversion_rate_pct:18, hat_tricks:1, player_trophies_total:3, market_value_m:60, goals_per_game:0.24, intl_caps:22, free_kick_goals:5, penalty_record_pct:75 },
    meta:{ position:'Forward', club:'Bayern Munich', nationality:'France', form:'WWWWW', key_stat:"France's rising star · Top scorer in Bundesliga 2025" },
    tags:['olise','michael','france','bayern munich','forward','winger'] },
  { id:'zirkzee', name:'Joshua Zirkzee', shortName:'Zirkzee', categoryId:'football', subCategoryId:'players', emoji:'🇳🇱',
    stats:{ age:24, goals_international:5, assists_international:4, wc_goals:0, player_wc_titles:0, career_club_goals:65, ballon_dor:0, ucl_titles:0, peak_rating:84, current_rating:84, pace:78, shooting:78, passing:74, dribbling:78, defending:42, physicality:76, creativity:75, big_game_goals:2, conversion_rate_pct:18, hat_tricks:0, player_trophies_total:2, market_value_m:45, goals_per_game:0.21, intl_caps:18, free_kick_goals:1, penalty_record_pct:68 },
    meta:{ position:'Forward', club:'AC Milan', nationality:'Netherlands', form:'WWDWW', key_stat:"Netherlands' next generation centre forward" },
    tags:['zirkzee','joshua','netherlands','ac milan','striker','forward'] },
  { id:'richarlison', name:'Richarlison', shortName:'Richarlison', categoryId:'football', subCategoryId:'players', emoji:'🇧🇷',
    stats:{ age:28, goals_international:26, assists_international:8, wc_goals:3, player_wc_titles:0, career_club_goals:140, ballon_dor:0, ucl_titles:0, peak_rating:86, current_rating:84, pace:84, shooting:82, passing:72, dribbling:78, defending:50, physicality:78, creativity:74, big_game_goals:5, conversion_rate_pct:22, hat_tricks:2, player_trophies_total:5, market_value_m:45, goals_per_game:0.29, intl_caps:68, free_kick_goals:2, penalty_record_pct:78 },
    meta:{ position:'Forward', club:'Tottenham Hotspur', nationality:'Brazil', form:'WWWDL', key_stat:"Olympic gold 2021 · Brazil's WC2022 top scorer" },
    tags:['richarlison','brazil','tottenham','striker','forward'] },
  { id:'raphinha', name:'Raphinha', shortName:'Raphinha', categoryId:'football', subCategoryId:'players', emoji:'🇧🇷',
    stats:{ age:28, goals_international:24, assists_international:16, wc_goals:1, player_wc_titles:0, career_club_goals:130, ballon_dor:0, ucl_titles:0, peak_rating:88, current_rating:88, pace:86, shooting:82, passing:80, dribbling:86, defending:50, physicality:68, creativity:84, big_game_goals:4, conversion_rate_pct:24, hat_tricks:2, player_trophies_total:5, market_value_m:60, goals_per_game:0.28, intl_caps:62, free_kick_goals:4, penalty_record_pct:75 },
    meta:{ position:'Forward', club:'Barcelona', nationality:'Brazil', form:'WWWWW', key_stat:"UCL top scorer 2025 · Barcelona's star winger" },
    tags:['raphinha','brazil','barcelona','forward','winger'] },
  { id:'pulisic', name:'Christian Pulisic', shortName:'Pulisic', categoryId:'football', subCategoryId:'players', emoji:'🇺🇸',
    stats:{ age:27, goals_international:32, assists_international:20, wc_goals:2, player_wc_titles:0, career_club_goals:125, ballon_dor:0, ucl_titles:1, peak_rating:87, current_rating:87, pace:85, shooting:80, passing:78, dribbling:84, defending:55, physicality:72, creativity:82, big_game_goals:5, conversion_rate_pct:22, hat_tricks:1, player_trophies_total:4, market_value_m:50, goals_per_game:0.30, intl_caps:70, free_kick_goals:4, penalty_record_pct:78 },
    meta:{ position:'Forward', club:'AC Milan', nationality:'USA', form:'WDWWW', key_stat:"USA's captain · Most decorated American footballer" },
    tags:['pulisic','christian','usa','ac milan','forward','winger','captain america'] },
];

function writeEntities(entities, categoryId, subCategoryId) {
  const dir = path.join(ROOT, 'entities', categoryId, subCategoryId);
  fs.mkdirSync(dir, { recursive: true });

  for (const entity of entities) {
    fs.writeFileSync(path.join(dir, `${entity.id}.json`), JSON.stringify(entity, null, 2));
  }

  const index = {
    categoryId,
    subCategoryId,
    entities: entities.map(e => ({
      id: e.id,
      name: e.name,
      emoji: e.emoji,
      subCategoryId: e.subCategoryId,
      tags: e.tags,
    })),
  };
  fs.writeFileSync(path.join(dir, '_index.json'), JSON.stringify(index, null, 2));
  console.log(`✓ Wrote ${entities.length} ${subCategoryId} + _index.json → entities/${categoryId}/${subCategoryId}/`);
}

writeEntities(TEAMS, 'football', 'teams');
writeEntities(PLAYERS, 'football', 'players');
console.log(`Done. ${TEAMS.length} teams + ${PLAYERS.length} players ready for CDN.`);
